export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL";

export const LIST_COMPANY_REQUEST = "LIST_COMPANY_REQUEST";
export const LIST_COMPANY_SUCCESS = "LIST_COMPANY_SUCCESS";
export const LIST_COMPANY_FAIL = "LIST_COMPANY_FAIL";

export const LIST_ACTIVE_COMPANY_REQUEST = "LIST_ACTIVE_COMPANY_REQUEST";
export const LIST_ACTIVE_COMPANY_SUCCESS = "LIST_ACTIVE_COMPANY_SUCCESS";
export const LIST_ACTIVE_COMPANY_FAIL = "LIST_ACTIVE_COMPANY_FAIL";

export const EDIT_COMPANY_REQUEST = "EDIT_COMPANY_REQUEST";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";
