export const ADD_GENERIC_REQUEST = "ADD_GENERIC_REQUEST";
export const ADD_GENERIC_SUCCESS = "ADD_GENERIC_SUCCESS";
export const ADD_GENERIC_FAIL = "ADD_GENERIC_FAIL";

export const LIST_GENERIC_REQUEST = "LIST_GENERIC_REQUEST";
export const LIST_GENERIC_SUCCESS = "LIST_GENERIC_SUCCESS";
export const LIST_GENERIC_FAIL = "LIST_GENERIC_FAIL";

export const LIST_ACTIVE_GENERIC_REQUEST = "LIST_ACTIVE_GENERIC_REQUEST";
export const LIST_ACTIVE_GENERIC_SUCCESS = "LIST_ACTIVE_GENERIC_SUCCESS";
export const LIST_ACTIVE_GENERIC_FAIL = "LIST_ACTIVE_GENERIC_FAIL";

export const EDIT_GENERIC_REQUEST = "EDIT_GENERIC_REQUEST";
export const EDIT_GENERIC_SUCCESS = "EDIT_GENERIC_SUCCESS";
export const EDIT_GENERIC_FAIL = "EDIT_GENERIC_FAIL";

export const DELETE_GENERIC_REQUEST = "DELETE_GENERIC_REQUEST";
export const DELETE_GENERIC_SUCCESS = "DELETE_GENERIC_SUCCESS";
export const DELETE_GENERIC_FAIL = "DELETE_GENERIC_FAIL";
