export const ADD_USER_TYPE_REQUEST = "ADD_USER_TYPE_REQUEST";
export const ADD_USER_TYPE_SUCCESS = "ADD_USER_TYPE_SUCCESS";
export const ADD_USER_TYPE_FAIL = "ADD_USER_TYPE_FAIL";

export const GET_USER_TYPE_REQUEST = "GET_USER_TYPE_REQUEST";
export const GET_USER_TYPE_SUCCESS = "GET_USER_TYPE_SUCCESS";
export const GET_USER_TYPE_FAIL = "GET_USER_TYPE_FAIL";

export const DELETE_USER_TYPE_REQUEST = "DELETE_USER_TYPE_REQUEST";
export const DELETE_USER_TYPE_SUCCESS = "DELETE_USER_TYPE_SUCCESS";
export const DELETE_USER_TYPE_FAIL = "DELETE_USER_TYPE_FAIL";
