export const ADD_USER_TYPE_REQUEST = "ADD_USER_TYPE_REQUEST";
export const ADD_USER_TYPE_SUCCESS = "ADD_USER_TYPE_SUCCESS";
export const ADD_USER_TYPE_FAIL = "ADD_USER_TYPE_FAIL";

export const GET_USER_TYPE_REQUEST = "GET_USER_TYPE_REQUEST";
export const GET_USER_TYPE_SUCCESS = "GET_USER_TYPE_SUCCESS";
export const GET_USER_TYPE_FAIL = "GET_USER_TYPE_FAIL";

export const REMOVE_USER_TYPE_REQUEST = "REMOVE_USER_TYPE_REQUEST";
export const REMOVE_USER_TYPE_SUCCESS = "REMOVE_USER_TYPE_SUCCESS";
export const REMOVE_USER_TYPE_FAIL = "REMOVE_USER_TYPE_FAIL";
