export const ADD_MEDICINE_FORM_REQUEST = "ADD_MEDICINE_FORM_REQUEST";
export const ADD_MEDICINE_FORM_SUCCESS = "ADD_MEDICINE_FORM_SUCCESS";
export const ADD_MEDICINE_FORM_FAIL = "ADD_MEDICINE_FORM_FAIL";

export const LIST_MEDICINE_FORM_REQUEST = "LIST_MEDICINE_FORM_REQUEST";
export const LIST_MEDICINE_FORM_SUCCESS = "LIST_MEDICINE_FORM_SUCCESS";
export const LIST_MEDICINE_FORM_FAIL = "LIST_MEDICINE_FORM_FAIL";

export const LIST_ACTIVE_MEDICINE_FORM_REQUEST =
  "LIST_ACTIVE_MEDICINE_FORM_REQUEST";
export const LIST_ACTIVE_MEDICINE_FORM_SUCCESS =
  "LIST_ACTIVE_MEDICINE_FORM_SUCCESS";
export const LIST_ACTIVE_MEDICINE_FORM_FAIL = "LIST_ACTIVE_MEDICINE_FORM_FAIL";

export const EDIT_MEDICINE_FORM_REQUEST = "EDIT_MEDICINE_FORM_REQUEST";
export const EDIT_MEDICINE_FORM_SUCCESS = "EDIT_MEDICINE_FORM_SUCCESS";
export const EDIT_MEDICINE_FORM_FAIL = "EDIT_MEDICINE_FORM_FAIL";

export const DELETE_MEDICINE_FORM_REQUEST = "DELETE_MEDICINE_FORM_REQUEST";
export const DELETE_MEDICINE_FORM_SUCCESS = "DELETE_MEDICINE_FORM_SUCCESS";
export const DELETE_MEDICINE_FORM_FAIL = "DELETE_MEDICINE_FORM_FAIL";
