export const ADD_MEDICINE_REQUEST = "ADD_MEDICINE_REQUEST";
export const ADD_MEDICINE_SUCCESS = "ADD_MEDICINE_SUCCESS";
export const ADD_MEDICINE_FAIL = "ADD_MEDICINE_FAIL";

export const LIST_MEDICINE_REQUEST = "LIST_MEDICINE_REQUEST";
export const LIST_MEDICINE_SUCCESS = "LIST_MEDICINE_SUCCESS";
export const LIST_MEDICINE_FAIL = "LIST_MEDICINE_FAIL";

export const LIST_ACTIVE_MEDICINE_REQUEST = "LIST_ACTIVE_MEDICINE_REQUEST";
export const LIST_ACTIVE_MEDICINE_SUCCESS = "LIST_ACTIVE_MEDICINE_SUCCESS";
export const LIST_ACTIVE_MEDICINE_FAIL = "LIST_ACTIVE_MEDICINE_FAIL";

export const EDIT_MEDICINE_REQUEST = "EDIT_MEDICINE_REQUEST";
export const EDIT_MEDICINE_SUCCESS = "EDIT_MEDICINE_SUCCESS";
export const EDIT_MEDICINE_FAIL = "EDIT_MEDICINE_FAIL";

export const DELETE_MEDICINE_REQUEST = "DELETE_MEDICINE_REQUEST";
export const DELETE_MEDICINE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_FAIL = "DELETE_MEDICINE_FAIL";
