export const ADD_RACK_REQUEST = "ADD_RACK_REQUEST";
export const ADD_RACK_SUCCESS = "ADD_RACK_SUCCESS";
export const ADD_RACK_FAIL = "ADD_RACK_FAIL";

export const LIST_RACK_REQUEST = "LIST_RACK_REQUEST";
export const LIST_RACK_SUCCESS = "LIST_RACK_SUCCESS";
export const LIST_RACK_FAIL = "LIST_RACK_FAIL";

export const LIST_ACTIVE_RACK_REQUEST = "LIST_ACTIVE_RACK_REQUEST";
export const LIST_ACTIVE_RACK_SUCCESS = "LIST_ACTIVE_RACK_SUCCESS";
export const LIST_ACTIVE_RACK_FAIL = "LIST_ACTIVE_RACK_FAIL";

export const EDIT_RACK_REQUEST = "EDIT_RACK_REQUEST";
export const EDIT_RACK_SUCCESS = "EDIT_RACK_SUCCESS";
export const EDIT_RACK_FAIL = "EDIT_RACK_FAIL";

export const DELETE_RACK_REQUEST = "DELETE_RACK_REQUEST";
export const DELETE_RACK_SUCCESS = "DELETE_RACK_SUCCESS";
export const DELETE_RACK_FAIL = "DELETE_RACK_FAIL";
