export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAIL = "ADD_STORE_FAIL";

export const LIST_STORE_REQUEST = "LIST_STORE_REQUEST";
export const LIST_STORE_SUCCESS = "LIST_STORE_SUCCESS";
export const LIST_STORE_FAIL = "LIST_STORE_FAIL";

export const LIST_ACTIVE_STORE_REQUEST = "LIST_STORE_REQUEST";
export const LIST_ACTIVE_STORE_SUCCESS = "LIST_STORE_SUCCESS";
export const LIST_ACTIVE_STORE_FAIL = "LIST_STORE_FAIL";

export const EDIT_STORE_REQUEST = "EDIT_STORE_REQUEST";
export const EDIT_STORE_SUCCESS = "EDIT_STORE_SUCCESS";
export const EDIT_STORE_FAIL = "EDIT_STORE_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";
